### PR TITLE
Added latest drive/charging log on dashboard to get more a dashboard …

### PR DESCRIPTION
**Pull request by Pazekal90**
…feeling in there now that there is more space. It´s a shortcut for getting into logs and stay there if you want.

Maybe should deduplicate the get logs functionality in a more general way.

Bildschirmfoto 2019-07-26 um 19 25 45

### CODE REVIEW

**Comment by GPlay97** [comment]
Need to review it later. But consider that you are missing more information such as CEC, CED ;)

**Comment by Pazekal90** [comment]
Just wanted to have a fast way to see my latest log and use the dashboard as a real dashboard to some features not just viewing data. 

CEC and CED are only in detail. So i haven't added them to the dashboard. But good idea why not. Just tell me whether add or not :) With PnP devices those values are not saved, aren't they?

**Comment by GPlay97** [comment]
Screenshot_20190726_193723_com android chrome
No, I mean, that a normal EVNotify user sees more data on dashboard, so per default it does not fit on a single page without scrolling ;)

**Comment by Pazekal90** [comment]
Ok. I see. Yes I missed that.. but I will find a solution to get it into one screen. :) maybe today maybe tomorrow :)

**Comment by GPlay97** [comment]
Not that bad. It's okay to scroll a bit, as long as the relevant information is avaiable directly without any scrolling-

**Comment by Pazekal90** [comment]
Yeah but without scrolling it would be a lot better in my point of view. 😊

**Comment by Pazekal90** [comment]
Added another commit to optimize. So on iPhone X no scrolling is needed anymore.

Better?

Bildschirmfoto 2019-07-26 um 21 03 38

**Comment by Pazekal90** [comment]
@GPlay97 Now that the values are side by side there should be enough room for this section at the bottom.

**Comment by Pazekal90** [comment]
Closed. New one opened without conflicts

**Pull request closed without merging**
