### PR TITLE
More informations and less useless space on dashboard...

### PR DESCRIPTION
**Pull request by Pazekal90**
Removed generic top navigation to get more information on screen without scrolling. Repositioned logout to settings beause logout is rarely used on PWA. User should stay loggedin as long as possible. Placed app images on login screen and bottom toolbar. #branding. Changed some styles for minimal padding and more information.

### CODE REVIEW

**Comment by Pazekal90** [comment]
image
image
image

**Comment by GPlay97** [comment]
Thank you. I will think about it. Some good things are already implemented in your ideas.

**Comment by Pazekal90** [comment]
I have already tested this. Is it ok for you to get more Pull Requests like this one? It shouldn't be only more work for you. It should be a good and valueable extension :)

**Comment by GPlay97** [comment]
I highly appreciate any Pull Request. It really helps. 

You can create new ones.
It would be great if you can seperate them in smal pull requests. In this case it's simpler to merge the single change, because currently the PWA is in active development and changes a lot.

However, for some things I still need to think, if this is the optimal way / design, even when it's tested.
But I'm really open for new things.

I will come back again

**Comment by GPlay97** [comment]
Thank you for your ideas.
I have optimized it a bit.

The icon within the bottom navigation is not necessary in my case and make the experience worse. But thank you for the ideas (especially the other issues and suggestions you have created, e.g. submit on enter).

For now, I will close this, since most are done and some will not be implemented, because users don't find this useful with the icon.

However, feel free to create new suggestions or even Pull Requests. For PRs, please ensure that you only create one for each feature / bugfix. This makes merging and communication way easier. Especially in early development, when many things continuously changes.

**Pull request closed without merging**
